# Generated by Django 3.1.7 on 2021-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('roll_no', models.CharField(max_length=150, null=True)),
                ('marks', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
